name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libxkbcommon-x11-0 libxcb-xinerama0 libxcb-xinput0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxcb-xkb1 libxrender1 libxrandr2 libxi6 libxtst6 libxcomposite1 libxcursor1 libxdamage1 libxinerama1 libxss1 libxv1 libxxf86vm1 xvfb scrot
        python -m pip install --upgrade pip

    - name: Run application with Xvfb
      env:
        DISPLAY: :99
        QT_DEBUG_PLUGINS: 1
      run: |
        Xvfb :99 -screen 0 1024x768x16 &
        sleep 3  # Give Xvfb some time to start
        python pythonProject/main.py &
        sleep 5  # Give the application some time to start
        scrot /tmp/screenshot.png

    - name: Upload screenshot
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: /tmp/screenshot.png
